version: '3.4'

services:

  catalogdbSrs:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage
    depends_on:
      - catalogdbSrs
    ports:
      - "8000:80"